name: bharat_translit
description: Bharat Transliteration App — Flutter Frontend (Web + Android)
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter: { sdk: flutter }
  http: ^1.2.2
  flutter_secure_storage: ^9.2.2
  provider: ^6.1.2
  camera: ^0.10.6
  image_picker: ^1.1.2
  google_maps_flutter: ^2.9.0
  intl: ^0.19.0
  flutter_dotenv: ^5.1.0
  geolocator: ^13.0.1

dev_dependencies:
  flutter_test: { sdk: flutter }
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/env
